set dotenv-load

default:
    @just --list


# Aliases 
alias s := serve
alias m := migrate
alias b := build
alias t := test
alias mn := migrate-new
alias sw := swagger
alias db := docker-build
alias dr := docker-run
alias dbr := docker-build-run

# Serve the application
serve:
    go run . serve -c config.yaml


# Run migrations 
migrate:
    go run . migrate up -c config.yaml


# Build the application
build name = "main": test
    go build -o bin/{{name}} .

# Run tests
test:
    go test ./...

# Create new migration
migrate-new name:
    go run . migrate new {{name}} -c config.yaml

# Reset the database by stopping containers, recreating them, and running migrations
reset:
    docker compose down
    docker compose up -d
    sleep 1
    @just migrate

# Generate swagger docs or update them (you need to have gog installed)
swagger:
    gog swag init -g cmd/serve/serve.go

docker-build:
    docker build -t nayla-installments-mgmt-svc:latest -f devops/Dockerfile .

docker-run:
    docker run --rm --name nayla-installments-mgmt-svc nayla-installments-mgmt-svc:latest

docker-build-run: docker-build docker-run