services:
  postgres:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres_data:/bitnami/postgres/data
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: myusername
      POSTGRES_DB: mydatabase
volumes:
  postgres_data:
